/*
 * Copyright 2014-2022 joerg All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "VerticalLine.h"
#include "CFGEdge.h"
#include "HorizontalLine.h"
#include "VerticalLineOwner.h"
#include "CFGNode.h"
#include "CFGLayer.h"
#include <memory>

#include "assert.h"


CFGEdge* VerticalLine::getEdge()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BB3 begin
{
    return this->edge;
}
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BB3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int VerticalLine::getx() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BBD begin
{
    return x;
}
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BBD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int VerticalLine::getUppery() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BBF begin
{
    if(!this->upperHorizont) //todo this is slow but needed
    {
        if(edge->isDown())
        {
            return edge->getSrc()->gety() + edge->getSrc()->getHeight();
        }
        else
        {
            return edge->getDest()->gety();
        }
    }
    return this->upperHorizont->gety();
}
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BBF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int VerticalLine::getLowery() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BC1 begin
{
    if(!this->lowerHorizont) //todo this is slow but needed
    {
        if(edge->isDown())
        {
            return edge->getDest()->gety();
        }
        else
        {
            return edge->getSrc()->gety() + edge->getSrc()->getHeight();
        }
    }
    return this->lowerHorizont->gety();
}
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BC1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

VerticalLine* VerticalLine::getFirst()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BCB begin
{
    return edge->getVerticalLines()->begin()->get();
}
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BCB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

VerticalLine* VerticalLine::getNext()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BD8 begin
{
    if(lowerHorizont)
        return lowerHorizont->getLowerVertical();
    else
        return NULL;
}
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BD8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

VerticalLine* VerticalLine::getPrev()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BDA begin
{
    if(!upperHorizont)
        return nullptr;
    return upperHorizont->getUpperVertical();
}
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BDA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

HorizontalLine* VerticalLine::getLowerHorizont()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BDC begin
{
    return lowerHorizont;
}
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BDC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

HorizontalLine* VerticalLine::getUpperHorizont()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BDE begin
{
    return upperHorizont;
}
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BDE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

VerticalLineOwner *VerticalLine::getHolder()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BFC begin
{
    return owner;
}
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000BFC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int VerticalLine::getyUp() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000C00 begin
{
    return upperHorizont->gety();
}
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000C00 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int VerticalLine::getyDown() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000C02 begin
{
    return lowerHorizont->gety();
}
void VerticalLine::attach(VerticalLineOwner &holder, int hintx)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000C12 begin
{
    owner = &holder;
    holder.attachVerticalLine(*this,hintx);
}
// section -64--88--78-20-3797976a:1506cf30996:-8000:0000000000000C12 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void VerticalLine::setx(int x)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20-55cbe988:15071e72dc6:-8000:0000000000000BE5 begin
{
    this->x = x;
}
// section -64--88--78-20-55cbe988:15071e72dc6:-8000:0000000000000BE5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool VerticalLine::glue(VerticalLine& next)
{
    bool temp = usedLineBinder->tryBindNext(next.usedLineBinder);
    if(temp)
        getLowerHorizont()->getLayer()->hideLine(*getLowerHorizont());
    return temp;
}

bool VerticalLine::isIOLine() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20-55cbe988:15071e72dc6:-8000:0000000000000BF3 begin
{
    if(upperHorizont == nullptr || lowerHorizont == nullptr)
        return true;
    return false;
}
bool VerticalLine::isGlue() const
{
    return (usedLineBinder->getSize() != 1);
}
// section -64--88--78-20-55cbe988:15071e72dc6:-8000:0000000000000BF3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void VerticalLine::link(HorizontalLine &Horizont)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20--4061d8fd:15076c26818:-8000:0000000000000BEF begin
{
    this->lowerHorizont = &Horizont;
}
// section -64--88--78-20--4061d8fd:15076c26818:-8000:0000000000000BEF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void VerticalLine::setLine(LineBinder* binder)
{
    usedLineBinder = binder;
    usedLineBinder->addline(this);

}

VerticalLine::VerticalLine(HorizontalLine* Horizont, CFGEdge &edge)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--78-20--4061d8fd:15076c26818:-8000:0000000000000BF2 begin
{
    ownLineBinder = std::make_unique<LineBinder>();
    ownLineBinder->addline(this);
    usedLineBinder = ownLineBinder.get();
    
    this->edge = &edge;
    this->upperHorizont = Horizont;
    if(Horizont)
        Horizont->link(*this);
}
// section -64--88--78-20--4061d8fd:15076c26818:-8000:0000000000000BF2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int VerticalLine::getLineSize() const
{
    return edge->getVerticalLines()->size() - 1;
}

VerticalLineOwner* VerticalLine::getOwner()
{
    return owner;
}

void VerticalLine::setOwner(VerticalLineOwner& owner)
{
    this->owner = &owner;
}
int VerticalLine::getEdgeID()
{
    return edge->getID();
}
bool VerticalLine::canSeek(int xoffset)
{
   return usedLineBinder->canSeek(xoffset);
}

void VerticalLine::seek(int xoffset)
{
    usedLineBinder->seek(xoffset);
}
LineBinder* VerticalLine::getUsedLineBinder()
{
    return usedLineBinder;
}
